### PR TITLE
[ADD] libracycle_payroll

### PR DESCRIPTION
**Pull request by ajepe**
Add libracycle_payroll module

### CODE REVIEW

**Review by infovpcs — COMMENTED** [review]
Can you please update the author, website, and category information? 
The description looks incomplete for the purpose of this module. so let me know after making changes with this.

**Comment by ajepe** [comment]
Let me know when you are done with the review @infovpcs

**Review by infovpcs — COMMENTED** [review]
libracycle_payroll/security/ir.model.access.csv 
This file is not required as we are not adding any new model. you are inheriting hr contract object so please remove this file from the module.

**Comment by infovpcs** [comment]
Can you please update your branch with latest staging changes so I can easily merge without conflicts

**Pull request merged**
